### ISSUE TITLE
net-p2p/cpp-ethereum depends on non-existent package

### ISSUE THREAD

**Issue by l29ah** [bignaux/lorelei-overlay#5]
dev-libs/libjson-rpc-cpp, that is

**Comment by nado** [comment]
The master is gentoo and libjson-rpc-cpp exists in gentoo official overlay.

**Comment by l29ah** [comment]
Nah, you've just sneakily patched your ebuild in 683eb814a3d6a39e9a9988ce71af97949bb8dfe3 :P

**Comment by nado** [comment]
Ah, now I see why it failed, I can't remember what issue I faced back then anyway :D

**Comment by bignaux** [comment]
I don't do gentoo anymore, i've swtiched to nixos, far better, so far.

**Comment by bignaux** [comment]
emerge nix && nix-env -iA cpp-ethereum
